
# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties
# 上面的url会映射{application}-{profile}.properties对应的配置文件，
# 其中{label}对应Git上不同的分支，默认为master。我们可以尝试构造不同的url来访问不同的配置内容，
# 比如，要访问master分支，config-client应用的dev环境，就可以访问这个url：http://localhost:1201/config-client/dev/master，并获得如下返回：


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Me-zzg/config.git
          username: 15231820401@163.com
          password: Aa5s.+v..
server:
  port: 1201